if (!xsor.resourceData) xsor.resourceData = {};

xsor.resourceData.actors = {
	axel: {
		stateMachine: xsor.stateMachines.character_axel,
		sequenceData: [
			["Grand Upper", 30, "F,F,y"],
			["Dragon Smash", 1, "/F,x"],
			["Flurry", 1, "~60y"],
			["Jumping knee drop", 1, "/D,y"],
			["Jump in left", 1, "/_U_L,z"],
			["Jump in right", 1, "/_U_R,z"],
			["Jump out left", 1, "/_D_L,z"],
			["Jump out right", 1, "/_D_R,z"],
			["Jump left", 1, "/_L,z"],
			["Jump right", 1, "/_R,z"],
			["Jump in", 1, "/_U,z"],
			["Jump out", 1, "/_D,z"],
			["Jump still", 1, "z"],
			["Jumping knee", 1, "y"],
			["Jumping kick", 1, "y"],
			["Punch", 1, "y"],
			["Dragon Wing", 1, "x"],
			["UpLeft", 1, "/_U_L", true],
			["UpRight", 1, "/_U_R", true],
			["DownLeft", 1, "/_D_L", true],
			["DownRight", 1, "/_D_R", true],
			["Up", 1, "/_U", true],
			["Down", 1, "/_D", true],
			["Left", 1, "/_L", true],
			["Right", 1, "/_R", true]
		],
		actorConstants: {
			hitPoints             : 300,
			width                 : 42,
			height                : 80,
			jumpSpeedZ            : 30,
			animIdle              : "char_axel_idle",
			animMove              : "char_axel_walk",
			animJumpStart         : "char_axel_jump_start",
			animJumpRise          : "char_axel_jump_rise",
			animJumpFall          : "char_axel_jump_fall",
			animJumpLand          : "char_axel_jump_land",
			animGetHitHigh        : "char_axel_get_hit_high",
			animGetHitLow         : "char_axel_get_hit_low",
			animFall              : "char_axel_fall",
			animRest              : "char_axel_rest",
			animGetUp             : "char_axel_get_up",
			animKnockout          : "char_axel_knockout",
			audioKnockout         : "axel_knockout",
		}
	},

	shiva_sor3: {
		stateMachine: xsor.stateMachines.character_shiva_sor3,
		sequenceData: [
			["Cutter", 30, "F,F,y"],
			["Somersault", 1, "/F,x"],
			["Flurry", 1, "~60y"],
			["Jumping attack drop", 1, "/D,y"],
			["Jump in left", 1, "/_U_L,z"],
			["Jump in right", 1, "/_U_R,z"],
			["Jump out left", 1, "/_D_L,z"],
			["Jump out right", 1, "/_D_R,z"],
			["Jump left", 1, "/_L,z"],
			["Jump right", 1, "/_R,z"],
			["Jump in", 1, "/_U,z"],
			["Jump out", 1, "/_D,z"],
			["Jump still", 1, "z"],
			["Jumping attack still", 1, "y"],
			["Jumping attack", 1, "y"],
			["Punch", 1, "y"],
			["Standing Flame", 1, "x"],
			["UpLeft", 1, "/_U_L", true],
			["UpRight", 1, "/_U_R", true],
			["DownLeft", 1, "/_D_L", true],
			["DownRight", 1, "/_D_R", true],
			["Up", 1, "/_U", true],
			["Down", 1, "/_D", true],
			["Left", 1, "/_L", true],
			["Right", 1, "/_R", true]
		],
		actorConstants: {
			hitPoints             : 300,
			width                 : 42,
			height                : 82,
			moveSpeedX            : 90,
			moveSpeedY            : 45,
			moveSpeedZ            : 54,
			jumpSpeedX            : 112.5,
			jumpSpeedY            : 292.5,
			animIdle              : "char_shiva_sor3_idle",
			animMove              : "char_shiva_sor3_walk",
			animJumpStart         : "char_shiva_sor3_jump_start",
			animJumpRise          : "char_shiva_sor3_jump_rise",
			animJumpFall          : "char_shiva_sor3_jump_fall",
			animJumpLand          : "char_shiva_sor3_jump_land",
			animGetHitHigh        : "char_shiva_sor3_get_hit_high",
			animGetHitLow         : "char_shiva_sor3_get_hit_low",
			animFall              : "char_shiva_sor3_fall",
			animRest              : "char_shiva_sor3_rest",
			animGetUp             : "char_shiva_sor3_get_up",
			animKnockout          : "char_shiva_sor3_knockout"
		}
	},

	donovan: {
		stateMachine: xsor.stateMachines.npc_donovan,
		sequenceData: [
			["Punch", 1, "y"],
			["Uppercut", 1, "x"],
			["UpLeft", 1, "/_U_L", true],
			["UpRight", 1, "/_U_R", true],
			["DownLeft", 1, "/_D_L", true],
			["DownRight", 1, "/_D_R", true],
			["Up", 1, "/_U", true],
			["Down", 1, "/_D", true],
			["Left", 1, "/_L", true],
			["Right", 1, "/_R", true]
		],
		actorConstants: {
			hitPoints             : 150,
			width                 : 42,
			height                : 70,
			animIdle              : "npc_donovan_idle",
			animMove              : "npc_donovan_walk",
			animGetHitHigh        : "npc_donovan_get_hit_high",
			animGetHitLow         : "npc_donovan_get_hit_low",
			animFall              : "npc_donovan_fall",
			animRest              : "npc_donovan_rest",
			animGetUp             : "npc_donovan_get_up",
			animKnockout          : "npc_donovan_knockout"
		}
	},

	galsia: {
		stateMachine: xsor.stateMachines.npc_galsia,
		sequenceData: [
			["Punch", 1, "y"],
			["UpLeft", 1, "/_U_L", true],
			["UpRight", 1, "/_U_R", true],
			["DownLeft", 1, "/_D_L", true],
			["DownRight", 1, "/_D_R", true],
			["Up", 1, "/_U", true],
			["Down", 1, "/_D", true],
			["Left", 1, "/_L", true],
			["Right", 1, "/_R", true]
		],
		actorConstants: {
			hitPoints             : 150,
			width                 : 42,
			height                : 70,
			animIdle              : "npc_galsia_idle",
			animMove              : "npc_galsia_walk",
			animGetHitHigh        : "npc_galsia_get_hit_high",
			animGetHitLow         : "npc_galsia_get_hit_low",
			animFall              : "npc_galsia_fall",
			animRest              : "npc_galsia_rest",
			animGetUp             : "npc_galsia_get_up",
			animKnockout          : "npc_galsia_knockout"
		}
	},

	hakuyo: {
		stateMachine: xsor.stateMachines.npc_hakuyo,
		sequenceData: [
			["Fireball", 1, "/F,x"],
			["Kick", 1, "~30y"],
			["Jump in left", 1, "/_U_L,z"],
			["Jump in right", 1, "/_U_R,z"],
			["Jump out left", 1, "/_D_L,z"],
			["Jump out right", 1, "/_D_R,z"],
			["Jump left", 1, "/_L,z"],
			["Jump right", 1, "/_R,z"],
			["Jump in", 1, "/_U,z"],
			["Jump out", 1, "/_D,z"],
			["Jump still", 1, "z"],
			["Jumping attack", 1, "y"],
			["Punch", 1, "y"],
			["Punch strong", 1, "x"],
			["UpLeft", 1, "/_U_L", true],
			["UpRight", 1, "/_U_R", true],
			["DownLeft", 1, "/_D_L", true],
			["DownRight", 1, "/_D_R", true],
			["Up", 1, "/_U", true],
			["Down", 1, "/_D", true],
			["Left", 1, "/_L", true],
			["Right", 1, "/_R", true]
		],
		actorConstants: {
			hitPoints             : 250,
			width                 : 50,
			height                : 71,
			depth                 : 10,
			moveSpeedX            : 90,
			moveSpeedY            : 56.25,
			moveSpeedZ            : 56.25,
			jumpSpeedX            : 112.5,
			jumpSpeedY            : 292.5,
			animIdle              : "npc_hakuyo_idle",
			animMove              : "npc_hakuyo_walk",
			animJumpStart         : "npc_hakuyo_jump_start",
			animJumpRise          : "npc_hakuyo_jump_rise",
			animJumpFall          : "npc_hakuyo_jump_fall",
			animJumpLand          : "npc_hakuyo_jump_land",
			animGetHitHigh        : "npc_hakuyo_get_hit_high",
			animGetHitLow         : "npc_hakuyo_get_hit_low",
			animFall              : "npc_hakuyo_fall",
			animRest              : "npc_hakuyo_rest",
			animGetUp             : "npc_hakuyo_get_up",
			animKnockout          : "npc_hakuyo_knockout"
		}
	},

	raven: {
		stateMachine: xsor.stateMachines.npc_raven,
		sequenceData: [
			["knee", 1, "/F,x"],
			["kick low", 30, "y"],
			["kick mid", 30, "~30y"],
			["kick high", 1, "x"],
			["UpLeft", 1, "/_U_L", true],
			["UpRight", 1, "/_U_R", true],
			["DownLeft", 1, "/_D_L", true],
			["DownRight", 1, "/_D_R", true],
			["Up", 1, "/_U", true],
			["Down", 1, "/_D", true],
			["Left", 1, "/_L", true],
			["Right", 1, "/_R", true]
		],
		actorConstants: {
			hitPoints             : 250,
			width                 : 40,
			height                : 84,
			animIdle              : "npc_raven_idle",
			animMove              : "npc_raven_walk",
			animJumpLand          : "npc_raven_jump_land",
			animGetHitHigh        : "npc_raven_get_hit_high",
			animGetHitLow         : "npc_raven_get_hit_low",
			animFall              : "npc_raven_fall",
			animRest              : "npc_raven_rest",
			animGetUp             : "npc_raven_get_up",
			animKnockout          : "npc_raven_knockout"
		}
	},

	signal: {
		stateMachine: xsor.stateMachines.npc_signal,
		sequenceData: [
			["slide", 1, "/F,x"],
			["backhand", 30, "y"],
			["UpLeft", 1, "/_U_L", true],
			["UpRight", 1, "/_U_R", true],
			["DownLeft", 1, "/_D_L", true],
			["DownRight", 1, "/_D_R", true],
			["Up", 1, "/_U", true],
			["Down", 1, "/_D", true],
			["Left", 1, "/_L", true],
			["Right", 1, "/_R", true]
		],
		actorConstants: {
			hitPoints             : 200,
			width                 : 38,
			height                : 80,
			animIdle              : "npc_signal_idle",
			animMove              : "npc_signal_walk",
			animGetHitHigh        : "npc_signal_get_hit_high",
			animGetHitLow         : "npc_signal_get_hit_low",
			animFall              : "npc_signal_fall",
			animRest              : "npc_signal_rest",
			animGetUp             : "npc_signal_get_up",
			animKnockout          : "npc_signal_knockout"
		}
	},

	rbear: {
		stateMachine: xsor.stateMachines.npc_rbear,
		sequenceData: [
			["Uppercut", 1, "/F,x"],
			["Backhit", 1, "/y,z"],
			["Rush", 30, "F,F,y"],
			["Jump in left", 1, "/_U_L,z"],
			["Jump in right", 1, "/_U_R,z"],
			["Jump out left", 1, "/_D_L,z"],
			["Jump out right", 1, "/_D_R,z"],
			["Jump left", 1, "/_L,z"],
			["Jump right", 1, "/_R,z"],
			["Jump in", 1, "/_U,z"],
			["Jump out", 1, "/_D,z"],
			["Jump still", 1, "z"],
			["Jumping attack", 1, "y"],
			["Punch", 1, "y"],
			["Punch strong", 1, "x"],
			["UpLeft", 1, "/_U_L", true],
			["UpRight", 1, "/_U_R", true],
			["DownLeft", 1, "/_D_L", true],
			["DownRight", 1, "/_D_R", true],
			["Up", 1, "/_U", true],
			["Down", 1, "/_D", true],
			["Left", 1, "/_L", true],
			["Right", 1, "/_R", true]
		],
		actorConstants: {
			hitPoints             : 250,
			width                 : 46,
			height                : 85,
			depth                 : 10,
			moveSpeedX            : 90,
			moveSpeedY            : 56.25,
			moveSpeedZ            : 56.25,
			jumpSpeedX            : 112.5,
			jumpSpeedY            : 292.5,
			jumpSpeedZ            : 30,
			animIdle              : "npc_rbear_idle",
			animMove              : "npc_rbear_walk",
			animJumpStart         : "npc_rbear_jump_start",
			animJumpRise          : "npc_rbear_jump_rise",
			animJumpFall          : "npc_rbear_jump_fall",
			animJumpLand          : "npc_rbear_jump_land",
			animGetHitHigh        : "npc_rbear_get_hit_high",
			animGetHitLow         : "npc_rbear_get_hit_low",
			animFall              : "npc_rbear_fall",
			animRest              : "npc_rbear_rest",
			animGetUp             : "npc_rbear_get_up",
			animKnockout          : "npc_rbear_knockout"
		}
	},
	
	thug: {
		stateMachine: xsor.stateMachines.npc_thug,
		sequenceData: [
			["Punch", 1, "y"],
			["UpLeft", 1, "/_U_L", true],
			["UpRight", 1, "/_U_R", true],
			["DownLeft", 1, "/_D_L", true],
			["DownRight", 1, "/_D_R", true],
			["Up", 1, "/_U", true],
			["Down", 1, "/_D", true],
			["Left", 1, "/_L", true],
			["Right", 1, "/_R", true]
		],
		actorConstants: {
			hitPoints             : 150,
			width                 : 46,
			height                : 76,
			animIdle              : "npc_thug_idle",
			animMove              : "npc_thug_walk",
			animGetHitHigh        : "npc_thug_get_hit_high",
			animGetHitLow         : "npc_thug_get_hit_low",
			animFall              : "npc_thug_fall",
			animRest              : "npc_thug_rest",
			animGetUp             : "npc_thug_get_up",
			animKnockout          : "npc_thug_knockout"
		}
	},

	barbon: {
		stateMachine: xsor.stateMachines.npc_barbon,
		sequenceData: [
			["Snapkick", 1, "/F,x"],
			["Rip shirt", 1, "x"],
			["Rip shirt", 1, "y"],
			["Rip shirt", 1, "z"],
			["Punch", 1, "y"],
			["Spinkick", 1, "x"],
			["UpLeft", 1, "/_U_L", true],
			["UpRight", 1, "/_U_R", true],
			["DownLeft", 1, "/_D_L", true],
			["DownRight", 1, "/_D_R", true],
			["Up", 1, "/_U", true],
			["Down", 1, "/_D", true],
			["Left", 1, "/_L", true],
			["Right", 1, "/_R", true]
		],
		actorConstants: {
			hitPoints             : 250,
			width                 : 42,
			height                : 84,
			depth                 : 10,
			moveSpeedX            : 90,
			moveSpeedY            : 56.25,
			moveSpeedZ            : 56.25,
			jumpSpeedX            : 112.5,
			jumpSpeedY            : 292.5,
			jumpSpeedZ            : 30,
			animIdle              : "npc_barbon_idle",
			animMove              : "npc_barbon_walk",
			animGetHitHigh        : "npc_barbon_get_hit_high",
			animGetHitLow         : "npc_barbon_get_hit_low",
			animFall              : "npc_barbon_fall",
			animRest              : "npc_barbon_rest",
			animGetUp             : "npc_barbon_get_up",
			animKnockout          : "npc_barbon_knockout"
		}
	},

	jack: {
		stateMachine: xsor.stateMachines.npc_jack,
		sequenceData: [
			["Slash", 30, "F,F,y"],
			["Knife equip", 1, "/y,z"],
			["Knife throw", 1, "/F,x"],
			["Laugh", 1, "/y,x"],
			["Punch", 1, "y"],
			["Punch strong", 1, "x"],
			["UpLeft", 1, "/_U_L", true],
			["UpRight", 1, "/_U_R", true],
			["DownLeft", 1, "/_D_L", true],
			["DownRight", 1, "/_D_R", true],
			["Up", 1, "/_U", true],
			["Down", 1, "/_D", true],
			["Left", 1, "/_L", true],
			["Right", 1, "/_R", true]
		],
		actorConstants: {
			hitPoints             : 250,
			width                 : 41,
			height                : 69,
			depth                 : 10,
			moveSpeedX            : 90,
			moveSpeedY            : 56.25,
			moveSpeedZ            : 56.25,
			jumpSpeedX            : 112.5,
			jumpSpeedY            : 292.5,
			jumpSpeedZ            : 30,
			animIdle              : "npc_jack_idle",
			animMove              : "npc_jack_walk",
			animGetHitHigh        : "npc_jack_get_hit_high",
			animGetHitLow         : "npc_jack_get_hit_low",
			animFall              : "npc_jack_fall",
			animRest              : "npc_jack_rest",
			animGetUp             : "npc_jack_get_up",
			animKnockout          : "npc_jack_knockout"
		}
	},

	object_barrel: {
		stateMachine: xlib.genericStateMachines.object_smashable,
		sequenceData: [],
		actorConstants: {
			hitPoints             : 10,
			width                 : 30,
			height                : 49,
			directionsAllowed     : xlib.INSTANCEDIRECTION_LEFT,
			knockoutSpeedX        : 135,
			knockoutSpeedY        : -180,
			knockoutSpeedZ        : 0,
			animIdle              : "object_barrel_idle",
			animGetHitHigh        : "object_barrel_ko",
			animFall              : "object_barrel_ko",
			animRest              : "object_barrel_idle",
			animGetUp             : "object_barrel_idle",
			animKnockout          : "object_barrel_ko",
			audioKnockout         : "get_hit_metal2",
			audioGetHitLight      : "get_hit_metal2",
			audioGetHitStrong     : "get_hit_metal2",
			audioGetHitFierce     : "get_hit_metal2",
			audioGetHitKnockdown  : "get_hit_metal2",
			audioGetHitWeaponBlunt: "get_hit_metal2",
			audioGetHitWeaponSlash: "get_hit_metal2",
			audioGetHitWeaponStab : "get_hit_metal2",
			audioGetHitStrong2    : "get_hit_metal2",
			audioGetHitKnockdown2 : "get_hit_metal2"
		}
	},

	object_trashcan: {
		stateMachine: xlib.genericStateMachines.object_smashable,
		sequenceData: [],
		actorConstants: {
			hitPoints             : 10,
			width                 : 32,
			height                : 40,
			directionsAllowed     : xlib.INSTANCEDIRECTION_LEFT,
			knockoutSpeedX        : 135,
			knockoutSpeedY        : -180,
			knockoutSpeedZ        : 0,
			animIdle              : "object_trashcan_idle",
			animGetHitHigh        : "object_trashcan_ko",
			animFall              : "object_trashcan_ko",
			animRest              : "object_trashcan_idle",
			animGetUp             : "object_trashcan_idle",
			animKnockout          : "object_trashcan_ko",
			audioKnockout         : "get_hit_metal1",
			audioGetHitLight      : "get_hit_metal1",
			audioGetHitStrong     : "get_hit_metal1",
			audioGetHitFierce     : "get_hit_metal1",
			audioGetHitKnockdown  : "get_hit_metal1",
			audioGetHitWeaponBlunt: "get_hit_metal1",
			audioGetHitWeaponSlash: "get_hit_metal1",
			audioGetHitWeaponStab : "get_hit_metal1",
			audioGetHitStrong2    : "get_hit_metal1",
			audioGetHitKnockdown2 : "get_hit_metal1"
		}
	},

	object_parkbin: {
		stateMachine: xlib.genericStateMachines.object_smashable,
		sequenceData: [],
		actorConstants: {
			hitPoints             : 10,
			width                 : 32,
			height                : 64,
			directionsAllowed     : xlib.INSTANCEDIRECTION_LEFT,
			knockoutSpeedX        : 135,
			knockoutSpeedY        : -180,
			knockoutSpeedZ        : 0,
			animIdle              : "object_parkbin_idle",
			animGetHitHigh        : "object_parkbin_ko",
			animFall              : "object_parkbin_ko",
			animRest              : "object_parkbin_idle",
			animGetUp             : "object_parkbin_idle",
			animKnockout          : "object_parkbin_ko",
			audioKnockout         : "get_hit_metal1",
			audioGetHitLight      : "get_hit_metal1",
			audioGetHitStrong     : "get_hit_metal1",
			audioGetHitFierce     : "get_hit_metal1",
			audioGetHitKnockdown  : "get_hit_metal1",
			audioGetHitWeaponBlunt: "get_hit_metal1",
			audioGetHitWeaponSlash: "get_hit_metal1",
			audioGetHitWeaponStab : "get_hit_metal1",
			audioGetHitStrong2    : "get_hit_metal1",
			audioGetHitKnockdown2 : "get_hit_metal1"
		}
	},

	object_arcademachine: {
		stateMachine: xlib.genericStateMachines.object_smashable,
		sequenceData: [],
		actorConstants: {
			hitPoints             : 10,
			width                 : 50,
			height                : 80,
			directionsAllowed     : xlib.INSTANCEDIRECTION_LEFT,
			knockoutSpeedX        : 135,
			knockoutSpeedY        : -180,
			knockoutSpeedZ        : 0,
			animIdle              : "object_arcademachine_idle",
			animGetHitHigh        : "object_arcademachine_ko",
			animFall              : "object_arcademachine_ko",
			animRest              : "object_arcademachine_idle",
			animGetUp             : "object_arcademachine_idle",
			animKnockout          : "object_arcademachine_ko",
			audioKnockout         : "get_hit_shatter",
			audioGetHitLight      : "get_hit_shatter",
			audioGetHitStrong     : "get_hit_shatter",
			audioGetHitFierce     : "get_hit_shatter",
			audioGetHitKnockdown  : "get_hit_shatter",
			audioGetHitWeaponBlunt: "get_hit_shatter",
			audioGetHitWeaponSlash: "get_hit_shatter",
			audioGetHitWeaponStab : "get_hit_shatter",
			audioGetHitStrong2    : "get_hit_shatter",
			audioGetHitKnockdown2 : "get_hit_shatter"
		}
	},
	
	item_chicken: {
		stateMachine: xlib.genericStateMachines.item,
		sequenceData: [],
		actorConstants: {
			hitPoints             : 10,
			width                 : 24,
			height                : 22,
			directionsAllowed     : xlib.INSTANCEDIRECTION_RIGHT,
			knockoutSpeedX        : 135,
			knockoutSpeedY        : -180,
			knockoutSpeedZ        : 0,
			animIdle              : "item_chicken_idle",
			animGetHitHigh        : "item_chicken_idle",
			animFall              : "item_chicken_idle",
			animRest              : "item_chicken_idle",
			animGetUp             : "item_chicken_idle",
			animKnockout          : "item_chicken_idle",
			audioKnockout         : "item_chicken_idle",
			audioGetHitLight      : "item_chicken_idle",
			audioGetHitStrong     : "item_chicken_idle",
			audioGetHitFierce     : "item_chicken_idle",
			audioGetHitKnockdown  : "item_chicken_idle",
			audioGetHitWeaponBlunt: "item_chicken_idle",
			audioGetHitWeaponSlash: "item_chicken_idle",
			audioGetHitWeaponStab : "item_chicken_idle",
			audioGetHitStrong2    : "item_chicken_idle",
			audioGetHitKnockdown2 : "item_chicken_idle"
		}
	},
	
	item_oneup: {
		stateMachine: xlib.genericStateMachines.item,
		sequenceData: [],
		actorConstants: {
			hitPoints             : 10,
			width                 : 16,
			height                : 15,
			directionsAllowed     : xlib.INSTANCEDIRECTION_RIGHT,
			knockoutSpeedX        : 135,
			knockoutSpeedY        : -180,
			knockoutSpeedZ        : 0,
			animIdle              : "item_oneup_idle",
			animGetHitHigh        : "item_oneup_idle",
			animFall              : "item_oneup_idle",
			animRest              : "item_oneup_idle",
			animGetUp             : "item_oneup_idle",
			animKnockout          : "item_oneup_idle",
			audioKnockout         : "item_oneup_idle",
			audioGetHitLight      : "item_oneup_idle",
			audioGetHitStrong     : "item_oneup_idle",
			audioGetHitFierce     : "item_oneup_idle",
			audioGetHitKnockdown  : "item_oneup_idle",
			audioGetHitWeaponBlunt: "item_oneup_idle",
			audioGetHitWeaponSlash: "item_oneup_idle",
			audioGetHitWeaponStab : "item_oneup_idle",
			audioGetHitStrong2    : "item_oneup_idle",
			audioGetHitKnockdown2 : "item_oneup_idle"
		}
	},
	
	item_apple: {
		stateMachine: xlib.genericStateMachines.item,
		sequenceData: [],
		actorConstants: {
			hitPoints             : 10,
			width                 : 16,
			height                : 16,
			directionsAllowed     : xlib.INSTANCEDIRECTION_RIGHT,
			knockoutSpeedX        : 135,
			knockoutSpeedY        : -180,
			knockoutSpeedZ        : 0,
			animIdle              : "item_apple_idle",
			animGetHitHigh        : "item_apple_idle",
			animFall              : "item_apple_idle",
			animRest              : "item_apple_idle",
			animGetUp             : "item_apple_idle",
			animKnockout          : "item_apple_idle",
			audioKnockout         : "item_apple_idle",
			audioGetHitLight      : "item_apple_idle",
			audioGetHitStrong     : "item_apple_idle",
			audioGetHitFierce     : "item_apple_idle",
			audioGetHitKnockdown  : "item_apple_idle",
			audioGetHitWeaponBlunt: "item_apple_idle",
			audioGetHitWeaponSlash: "item_apple_idle",
			audioGetHitWeaponStab : "item_apple_idle",
			audioGetHitStrong2    : "item_apple_idle",
			audioGetHitKnockdown2 : "item_apple_idle"
		}
	},
	
	item_gold: {
		stateMachine: xlib.genericStateMachines.item,
		sequenceData: [],
		actorConstants: {
			hitPoints             : 10,
			width                 : 16,
			height                : 13,
			directionsAllowed     : xlib.INSTANCEDIRECTION_RIGHT,
			knockoutSpeedX        : 135,
			knockoutSpeedY        : -180,
			knockoutSpeedZ        : 0,
			animIdle              : "item_gold_idle",
			animGetHitHigh        : "item_gold_idle",
			animFall              : "item_gold_idle",
			animRest              : "item_gold_idle",
			animGetUp             : "item_gold_idle",
			animKnockout          : "item_gold_idle",
			audioKnockout         : "item_gold_idle",
			audioGetHitLight      : "item_gold_idle",
			audioGetHitStrong     : "item_gold_idle",
			audioGetHitFierce     : "item_gold_idle",
			audioGetHitKnockdown  : "item_gold_idle",
			audioGetHitWeaponBlunt: "item_gold_idle",
			audioGetHitWeaponSlash: "item_gold_idle",
			audioGetHitWeaponStab : "item_gold_idle",
			audioGetHitStrong2    : "item_gold_idle",
			audioGetHitKnockdown2 : "item_gold_idle"
		}
	},
	
	item_money: {
		stateMachine: xlib.genericStateMachines.item,
		sequenceData: [],
		actorConstants: {
			hitPoints             : 10,
			width                 : 16,
			height                : 16,
			directionsAllowed     : xlib.INSTANCEDIRECTION_RIGHT,
			knockoutSpeedX        : 135,
			knockoutSpeedY        : -180,
			knockoutSpeedZ        : 0,
			animIdle              : "item_money_idle",
			animGetHitHigh        : "item_money_idle",
			animFall              : "item_money_idle",
			animRest              : "item_money_idle",
			animGetUp             : "item_money_idle",
			animKnockout          : "item_money_idle",
			audioKnockout         : "item_money_idle",
			audioGetHitLight      : "item_money_idle",
			audioGetHitStrong     : "item_money_idle",
			audioGetHitFierce     : "item_money_idle",
			audioGetHitKnockdown  : "item_money_idle",
			audioGetHitWeaponBlunt: "item_money_idle",
			audioGetHitWeaponSlash: "item_money_idle",
			audioGetHitWeaponStab : "item_money_idle",
			audioGetHitStrong2    : "item_money_idle",
			audioGetHitKnockdown2 : "item_money_idle"
		}
	}
	
};