if (!xsor.resourceData) xsor.resourceData = {};

xsor.resourceData.audio = {
	jump:                  ["audio/jump.mp3"                 , "audio/jump.ogg"]                 ,
	land:                  ["audio/land.mp3"                 , "audio/land.ogg"]                 ,
	swing:                 ["audio/swing.mp3"                , "audio/swing.ogg"]                ,
	get_hit_light1:        ["audio/get_hit_light1.mp3"       , "audio/get_hit_light1.ogg"]       ,
	get_hit_light2:        ["audio/get_hit_light2.mp3"       , "audio/get_hit_light2.ogg"]       ,
	get_hit_strong1:       ["audio/get_hit_strong1.mp3"      , "audio/get_hit_strong1.ogg"]      ,
	get_hit_strong2:       ["audio/get_hit_strong2.mp3"      , "audio/get_hit_strong2.ogg"]      ,
	get_hit_fierce1:       ["audio/get_hit_fierce1.mp3"      , "audio/get_hit_fierce1.ogg"]      ,
	get_hit_fierce2:       ["audio/get_hit_fierce2.mp3"      , "audio/get_hit_fierce2.ogg"]      ,
	get_hit_knockdown1:    ["audio/get_hit_knockdown1.mp3"   , "audio/get_hit_knockdown1.ogg"]   ,
	get_hit_knockdown2:    ["audio/get_hit_knockdown2.mp3"   , "audio/get_hit_knockdown2.ogg"]   ,
	get_hit_knockdown3:    ["audio/get_hit_knockdown3.mp3"   , "audio/get_hit_knockdown3.ogg"]   ,
	get_hit_weapon_blunt:  ["audio/get_hit_weapon_blunt.mp3" , "audio/get_hit_weapon_blunt.ogg"] ,
	get_hit_weapon_slash:  ["audio/get_hit_weapon_slash.mp3" , "audio/get_hit_weapon_slash.ogg"] ,
	get_hit_weapon_stab:   ["audio/get_hit_weapon_stab.mp3"  , "audio/get_hit_weapon_stab.ogg"]  ,
	get_hit_fireball:      ["audio/get_hit_fireball.mp3"     , "audio/get_hit_fireball.ogg"]     ,
	get_hit_metal1:        ["audio/get_hit_metal1.mp3"       , "audio/get_hit_metal1.ogg"]       ,
	get_hit_metal2:        ["audio/get_hit_metal2.mp3"       , "audio/get_hit_metal2.ogg"]       ,
	axel_dragon_wing:      ["audio/axel_dragon_wing.mp3"     , "audio/axel_dragon_wing.ogg"]     ,
	axel_grand_upper:      ["audio/axel_grand_upper.mp3"     , "audio/axel_grand_upper.ogg"]     ,
	axel_yell:             ["audio/axel_yell.mp3"            , "audio/axel_yell.ogg"]            ,
	special1:              ["audio/special1.mp3"             , "audio/special1.ogg"]             ,
	hit_ground:            ["audio/get_hit_knockdown2.mp3"   , "audio/get_hit_knockdown2.ogg"]   ,
	yell14:                ["audio/yell14.mp3"               , "audio/yell14.ogg"]               ,
	shiva_sor3_somersault: ["audio/shiva_sor3_somersault.mp3", "audio/shiva_sor3_somersault.ogg"],
	knockout1:             ["audio/knockout1.mp3"            , "audio/knockout1.ogg"]            ,
	hakuyo_yell:           ["audio/hakuyo_yell.mp3"          , "audio/hakuyo_yell.ogg"]          ,
	signal_slide:          ["audio/signal_slide.mp3"         , "audio/signal_slide.ogg"]         ,
	knockout2:             ["audio/knockout2.mp3"            , "audio/knockout2.ogg"]            ,
	knockout3:             ["audio/knockout3.mp3"            , "audio/knockout3.ogg"]            ,
	get_hit_shatter:       ["audio/get_hit_shatter.mp3"      , "audio/get_hit_shatter.ogg"]      ,
	axel_knockout:         ["audio/axel_knockout.mp3"        , "audio/axel_knockout.ogg"]        
};